### PR TITLE
Use unsafe bit shift

### PR DESCRIPTION
**Pull request by newhoggy**
As an optimisation

### CODE REVIEW

**Comment by Kheldar** [comment]
To ask the obvious question: Is this safe? Is there much chance that this could screw someone over if they used it incorrectly?

**Comment by newhoggy** [comment]
Still passes all the tests.

**Comment by newhoggy** [comment]
I've only been able to discern micro-benchmarking improvements.  No measurable performance on real data, that I can see.

**Comment by Kheldar** [comment]
¯\_(ツ)_/¯ Sure, if you think it's a good idea.

**Pull request closed without merging**
